[package]
name = "arazzo2mermaid"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
yaml_serde = "0.10"
serde_json = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
base64 = "0.22"
open = "5"

